### PR TITLE
Remove body of non-text content-types

### LINKED ISSUE #1: RangeError: Maximum call stack size exceeded
What pattern would you use to prevent RangeError?

Currently, I add links to queue by calling `done` inside `done`:

```
    spider = new Spider({
      concurrent: 10, logs: true,
      headers: {
        'user-agent': 'codeclub_lesson_builder'
      },
      error: function(url, err){
        console.log('got err ', url, err);
      },
      done: function() {
        console.log('done');
        browserSync.exit();
        cb();
      }
    });
    var resources = {};
    var done = function(doc){
      if (doc.url.search('http://localhost:3000/') === 0) {
        // we are on localhost
        doc.$('a').each(function(){
          var href = this.attr('href');
          var url = doc.resolve(href);
          if (url in resources) {
            // already added
            return;
          }
          console.log('Found', url, doc.url);
          spider.queue(url, done);
          resources[url] = true;
        });
      }
    };
    var start = 'http://localhost:3000/index.html';
    spider.queue(start, done);
    resources[start] = true;
```

### PR DESCRIPTION
**Pull request by arve0**
Will you approve this? Fixes #1.

### CODE REVIEW

**Comment by flesler** [comment]
The thing is, it's more complex than that. There's all the application/\* content-type branch where some are plain text and some aren't.

I'm not sure what the best solution is, but if I stick that conditional there I might be leaving other users with no chance of retrieving any file it skips.

The document object you get on the callback has the response object which has the headers. I'd say move that `if` into your callback.

``` js
var done = function(doc) {
  if (!/text|javascript|css|json|xml/i.test(doc.res.headers['content-type'])) {
    return;
  }
  ...
};
```

Do note that this is still inefficient, you could be fetching a 5mb zip file only to discard it later.
I'd advise you to somehow skip these links before queuing them in, it surely can be done if you know the markup well.

**Comment by arve0** [comment]
Thanks, it works! :+1: Wasn't able to wrap my head around it, see now that the `$` is lazy.

**Comment by flesler** [comment]
Yeah, I assumed many would be used or discarded based on URL without the need to parse the document

**Comment by arve0** [comment]
Great code btw. Clean and simple, like it. Mind if I send a PR with an example in the README?

**Comment by flesler** [comment]
I don't mind at all, you mean a generic example?

**Pull request closed without merging**
